package gym.management.system;

import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import project.ConnectionProvider;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dawood Khatri
 */
public class CustomerDetails extends javax.swing.JFrame {

    /**
     * Creates new form ListOfMembers
     */
    public CustomerDetails() {
        initComponents();
        show_customer();
    }
       public ArrayList<customers2>customerList(){
            ArrayList<customers2>customersList = new ArrayList<>();
             try{
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
           String url = "jdbc:sqlserver://localhost:1433;databaseName=gymlogindb;user=sa;password=msk1234;encrypt=false";
           Connection con =DriverManager.getConnection(url);
           String query = "Select * from customers2";
           Statement st = con.createStatement();
           ResultSet rs = st.executeQuery(query);
           customers2 Customer_1;
           while(rs.next()){
               Customer_1= new customers2(rs.getString("sno"),rs.getString("name"),rs.getString("mobilenumber"),rs.getString("email"),rs.getString("gender"),rs.getString("fathername"),rs.getString("address"),rs.getString("height"),rs.getString("weight"),rs.getString("membership"),rs.getString("gymtime"),rs.getString("cnicnumber"),rs.getString("age"),rs.getString("amount"));
               customersList.add(Customer_1); 
           }
             }
              catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
             return customersList; 
       }
       public void show_customer(){
            ArrayList<customers2> details = customerList();
            DefaultTableModel model = (DefaultTableModel )jTable_Display_Customer.getModel(); 
            Object[] row = new Object[14];
             for(int i=0;i<details.size();i++){
                 row[0]=details.get(i).getsno();
                 row[1]=details.get(i).getname();
                 row[2]=details.get(i).getmobilenumber();
                 row[3]=details.get(i).getemail();
                 row[4]=details.get(i).getgender();
                 row[5]=details.get(i).getfathername();
                 row[6]=details.get(i).getaddress();
                 row[7]=details.get(i).getheight();
                 row[8]=details.get(i).getweight();
                 row[9]=details.get(i).getmembership();
                 row[10]=details.get(i).getgymtime();
                 row[11]=details.get(i).getcnicnumber();
                 row[12]=details.get(i).getage();
                 row[13]=details.get(i).getamount();
                 model.addRow(row);
             
             } 
       } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display_Customer = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 118, 221));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/list of members.png"))); // NOI18N
        jLabel2.setText("customer details");

        jTable_Display_Customer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Member ID", "Name", "Mobile Number", "Email", "Gender", "Father Name", "Address", "Height", "Weight", "Membership", "Gymtime", "CNIC Number", "Age", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable_Display_Customer);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(232, 232, 232))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Display_Customer;
    // End of variables declaration//GEN-END:variables


}