package gym.management.system;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dawood Khatri
 */
public class TrainerEntry extends javax.swing.JFrame {

    private JTextField trainerIDField;
    private JComboBox<String> morningAttendanceCombo;
    private JComboBox<String> eveningAttendanceCombo;

    public TrainerEntry() {
        initComponents();
        // Frame setup
        setTitle("Trainer Attendance");
        setSize(400, 200);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);

        // Panel setup
        JPanel mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayout(4, 2));

        // Components setup
        JLabel trainerIDLabel = new JLabel("Trainer ID:");
        trainerIDField = new JTextField();

        JLabel morningLabel = new JLabel("Morning Time:");
        morningAttendanceCombo = new JComboBox<>(new String[]{"Absent", "Present"});

        JLabel eveningLabel = new JLabel("Evening Time:");
        eveningAttendanceCombo = new JComboBox<>(new String[]{"Absent", "Present"});

        JButton submitButton = new JButton("Submit");
        submitButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                submitAttendance();
            }
        });

        // Add components to panel
        mainPanel.add(trainerIDLabel);
        mainPanel.add(trainerIDField);

        mainPanel.add(morningLabel);
        mainPanel.add(morningAttendanceCombo);

        mainPanel.add(eveningLabel);
        mainPanel.add(eveningAttendanceCombo);

        mainPanel.add(new JLabel()); // Empty label for spacing
        mainPanel.add(submitButton);

        // Set layout and add panel to frame
        setLayout(new BorderLayout());
        add(mainPanel, BorderLayout.CENTER);
    }

    private void submitAttendance() {
        String trainerID = trainerIDField.getText();
        String morningAttendance = (String) morningAttendanceCombo.getSelectedItem();
        String eveningAttendance = (String) eveningAttendanceCombo.getSelectedItem();

        // Here, you can perform actions like saving the attendance to a database or displaying it in a different way.
        // For now, let's just print the values.
        System.out.println("Trainer ID: " + trainerID);
        System.out.println("Morning Attendance: " + morningAttendance);
        System.out.println("Evening Attendance: " + eveningAttendance);

        // You can add more logic based on your requirements.

        // Reset the fields after submission
        trainerIDField.setText("");
        morningAttendanceCombo.setSelectedIndex(0);
        eveningAttendanceCombo.setSelectedIndex(0);
    }
    /**
     * Creates new form TrainerEntry
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
