package gym.management.system;
import java.sql.*;
import java.beans.Statement;
import java.util.ArrayList;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dawood Khatri
 */
public class TrainerDetails extends javax.swing.JFrame {

    /**
     * Creates new form TrainerDetails
     */
    public TrainerDetails() {
        initComponents();
        show_trainer();
    }
 public ArrayList<Trainers1>trainerList(){
            ArrayList<Trainers1>trainerList = new ArrayList<>();
             try{
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
           String url = "jdbc:sqlserver://localhost:1433;databaseName=gymlogindb;user=sa;password=msk1234;encrypt=false";
           Connection con =DriverManager.getConnection(url);
           String query = "Select * from Trainers1";
           java.sql.Statement st = con.createStatement();
           ResultSet rs = st.executeQuery(query);
           Trainers1 trainer_1;
           while(rs.next()){
               trainer_1= new Trainers1(rs.getInt("sno"),rs.getString("name"),rs.getString("mobilenumber"),rs.getString("email"),rs.getString("gender"),rs.getString("fathername"),rs.getString("address"),rs.getString("height"),rs.getInt("weight"),rs.getString("minimumagreement"),rs.getString("membership"),rs.getString("gymtime"),rs.getString("cnicnumber"),rs.getInt("age"),rs.getInt("amount"));
               trainerList.add(trainer_1); 
           }
             }
              catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
             return trainerList; 
       }
       public void show_trainer(){
            ArrayList<Trainers1> details = trainerList();
            DefaultTableModel model = (DefaultTableModel )jTable_Display_trainers.getModel(); 
            Object[] row = new Object[15];
             for(int i=0;i<details.size();i++){
                 row[0]=details.get(i).getsno();
                 row[1]=details.get(i).getname();
                 row[2]=details.get(i).getmobilenumber();
                 row[3]=details.get(i).getemail();
                 row[4]=details.get(i).getgender();
                 row[5]=details.get(i).getfathername();
                 row[6]=details.get(i).getaddress();
                 row[7]=details.get(i).getheight();
                 row[8]=details.get(i).getweight();
                 row[9]=details.get(i).getminimumagreement();
                 row[10]=details.get(i).getmembership();
                 row[11]=details.get(i).getgymtime();
                 row[12]=details.get(i).getcnicnumber();
                 row[13]=details.get(i).getage();
                 row[14]=details.get(i).getamount();
                 model.addRow(row);
             
             } 
       } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display_trainers = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 118, 221));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/list of members.png"))); // NOI18N
        jLabel2.setText("Trainer details");

        jTable_Display_trainers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Member ID", "Name", "Mobile Number", "Email", "Gender", "Father Name", "Address", "Height", "Weight", "MinimumAgreement", "Membership", "GymTime", "CNIC Number", "Age", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable_Display_trainers);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(258, 258, 258))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Display_trainers;
    // End of variables declaration//GEN-END:variables
}
